# Generated by Django 5.2.1 on 2026-03-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this account pool.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text="Optional description of the pool's purpose.")),
                ('provider', models.CharField(blank=True, default='', help_text="Provider/service name used to group pools (e.g. 'PlutoTV', 'MyIPTV').", max_length=255)),
                ('strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_used', 'Least Used'), ('sequential', 'Sequential')], default='round_robin', help_text='Strategy used when selecting an account from the pool.', max_length=20)),
                ('max_streams_per_account', models.IntegerField(default=1, help_text='Maximum concurrent streams allowed per account in this pool.')),
                ('enabled', models.BooleanField(default=True, help_text='Disable to stop the pool from being used for stream assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Pool',
                'verbose_name_plural': 'Account Pools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountPoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers = higher priority (used by sequential strategy).')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='The M3U account that is a member of the pool.', on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='m3u.m3uaccount')),
                ('pool', models.ForeignKey(help_text='The pool this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='m3u.accountpool')),
            ],
            options={
                'verbose_name': 'Account Pool Membership',
                'verbose_name_plural': 'Account Pool Memberships',
                'ordering': ['priority', 'added_at'],
                'unique_together': {('pool', 'account')},
            },
        ),
        migrations.CreateModel(
            name='StreamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(help_text='Opaque identifier for the stream being served (e.g. channel ID or URL hash).', max_length=512)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='Set when the stream is released; null means the assignment is still active.', null=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='False when the stream has been released.')),
                ('account', models.ForeignKey(help_text='The specific account serving this stream.', on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='m3u.m3uaccount')),
                ('pool', models.ForeignKey(help_text='The pool that owns this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='m3u.accountpool')),
            ],
            options={
                'verbose_name': 'Stream Assignment',
                'verbose_name_plural': 'Stream Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['pool', 'active'], name='m3u_streama_pool_id_88d707_idx'), models.Index(fields=['account', 'active'], name='m3u_streama_account_c3daeb_idx')],
            },
        ),
    ]
